/**
 * Wire protocol for online matches between two human players. This module holds
 * the two things a BARE schema cannot express — the **handshake** (which happens
 * in URL query params, before any message can be sent) and the **framing** (one
 * tag octet in front of each payload). The message shapes themselves live in
 * `../schema/messages.bare` and reach code as `@drone-directive/protocol/codec`,
 * generated by `npm run codegen -w protocol` and committed.
 *
 * Nothing here has a runtime dependency, on purpose: the relay Worker imports
 * this module on its hot path and must be able to route a frame without linking
 * a decoder. See `.docs/multiplayer.md` and `.docs/server-relay.md`.
 */

/** Bumped on any breaking wire change; clients send it, the relay rejects mismatches. */
export const PROTOCOL_VERSION = 15;

/** Room codes: fixed length, drawn from an unambiguous alphabet (no 0/O/1/I). */
export const ROOM_CODE_LENGTH = 4;
export const ROOM_CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

/**
 * Connection contract. A WebSocket must target a specific room before it opens, so
 * the create/join intent travels as URL query params rather than as messages:
 *   host:   `?room=<CODE>&create=1&v=<PROTOCOL_VERSION>&mapSize=<small|medium|large>&ai=<0-2>`
 *   guest:  `?room=<CODE>&v=<PROTOCOL_VERSION>`
 *   resume: `?room=<CODE>&v=<PROTOCOL_VERSION>&resume=<RESUME_TOKEN>`
 *   chat:   `/chat?chat=<CHAT_ID>&seat=<host|guest>&since=<SEQ>&v=<PROTOCOL_VERSION>`
 *
 * Chat travels the same way and for the same reason: the socket has to name the
 * chat (and the seat, and where the client left off) before it opens, so there is
 * no `hello` message to get wrong.
 */
export const QueryParam = {
  Room: 'room',
  Create: 'create',
  Version: 'v',
  MapSize: 'mapSize',
  /** Bot-controlled sides joining the two humans, `0..MAX_AI_OPPONENTS`. */
  Ai: 'ai',
  /**
   * Reclaiming a seat after a drop: the `resumeToken` that seat was issued in
   * `start`. It names the seat as well as proving the right to it, so there is no
   * separate host/guest param — the relay knows which of the two it matched.
   */
  Resume: 'resume',
  /** Chat: the relay-issued id of the chat object to attach to. */
  ChatId: 'chat',
  /** Chat: which seat this client holds, `host` or `guest`. */
  Seat: 'seat',
  /** Chat: the highest `seq` this client already has; the server replies with the gap. */
  Since: 'since',
} as const;

/**
 * Most bots a networked match can seat. The map deals one corner per side and the
 * two humans already hold two of the four.
 */
export const MAX_AI_OPPONENTS = 2;

/** Map presets, as spelled in the `mapSize` query param (the handshake is still text). */
export const WIRE_MAP_SIZES = ['small', 'medium', 'large'] as const;
export type WireMapSize = (typeof WIRE_MAP_SIZES)[number];

/** How often a peer attaches a `WorldCheck` (in ticks) — ~1s at 10Hz. */
export const DESYNC_CHECK_EVERY = 10;

// ---------------------------------------------------------------------------
// Resuming a dropped seat
// ---------------------------------------------------------------------------

/**
 * How long the relay holds a dropped seat open before the match really is over.
 *
 * A lockstep peer that loses its socket does not fall behind — both sides stop
 * advancing the moment one tick's input is missing — so the only thing a short
 * outage costs is the frames sent while it lasted. The relay keeps those and the
 * seat, and the survivor simply stalls, exactly as it already does for lag.
 */
export const RESUME_GRACE_MS = 20_000;

/**
 * Hard bound on the frames held for a dropped seat. At 30Hz the grace period can
 * only produce ~600, so this is a memory ceiling rather than a policy: if it is
 * ever hit the seat has missed more than it can be told about, and the relay
 * refuses the resume instead of handing back a stream with a hole in it.
 */
export const RESUME_BUFFER_FRAMES = 900;

/** Resume tokens are hex of 16 random bytes — opaque, unguessable, relay-issued. */
export const RESUME_TOKEN_LENGTH = 32;

// ---------------------------------------------------------------------------
// Chat
// ---------------------------------------------------------------------------

/** Path a chat socket connects to; anything else on the relay is a game room. */
export const CHAT_PATH = '/chat';

/** Chat ids are hex of 16 random bytes — opaque, unguessable, relay-issued. */
export const CHAT_ID_LENGTH = 32;

/** Seat names as they are spelled in the `seat` query param (the handshake is text). */
export const WIRE_CHAT_SEATS = ['host', 'guest'] as const;
export type WireChatSeat = (typeof WIRE_CHAT_SEATS)[number];

/** Longest a single message may be, after sanitizing; the server truncates rather than rejects. */
export const MAX_CHAT_TEXT_LENGTH = 500;

/** Most messages the server keeps (and replays); older ones are dropped after each insert. */
export const CHAT_HISTORY_LIMIT = 200;

/** A chat is erased this long after its *last* message — every post re-arms the timer. */
export const CHAT_RETENTION_MS = 7 * 24 * 60 * 60 * 1000;

/** Per-seat send budget. Generous for a conversation, useless for a flood. */
export const CHAT_RATE_LIMIT = { messages: 10, windowMs: 10_000 } as const;

/**
 * The bidi overrides, which let text render in an order it is not written in.
 * Deleted outright: they separate nothing, so removing one must not open a gap.
 */
const CHAT_BIDI_RE = /[\u200E\u200F\u202A-\u202E\u2066-\u2069]/g;

/**
 * C0 and C1 control codes, including the newlines and tabs a single-line log
 * would render as nothing. Replaced by a space rather than deleted: a newline is
 * a word separator, and deleting one would silently glue two words together. The
 * collapse pass right after removes whatever that leaves behind.
 */
// eslint-disable-next-line no-control-regex
const CHAT_CONTROL_RE = /[\u0000-\u001F\u007F-\u009F]/g;

/**
 * The one sanitizer, imported by both the Worker and the client so what the
 * sender sees and what the log stores can never disagree. Pure, and
 * dependency-free, because this module is on the relay's hot path.
 *
 * Returns `''` for anything that sanitizes away to nothing — callers read that as
 * "reject", which is why whitespace-only input never reaches the log.
 */
export function sanitizeChatText(raw: string): string {
  const collapsed = raw
    .normalize('NFC')
    .replace(CHAT_BIDI_RE, '')
    .replace(CHAT_CONTROL_RE, ' ')
    // Collapse runs (including the exotic Unicode spaces) so no one can push the
    // log around with three hundred blanks.
    .replace(/\s+/gu, ' ')
    .trim();
  if (collapsed.length <= MAX_CHAT_TEXT_LENGTH) return collapsed;
  // Truncation is by UTF-16 unit, so it can land between a surrogate pair and
  // leave half an emoji behind; drop the orphan rather than store a lone unit.
  const cut = collapsed.slice(0, MAX_CHAT_TEXT_LENGTH);
  const last = cut.charCodeAt(cut.length - 1);
  return (last >= 0xd800 && last <= 0xdbff ? cut.slice(0, -1) : cut).trim();
}

// ---------------------------------------------------------------------------
// Framing
// ---------------------------------------------------------------------------

/**
 * Which message a frame carries, as its leading octet. BARE has no envelope of
 * its own, and putting the discriminant *outside* the payload is what keeps the
 * relay dumb: it reads one byte to decide whether to forward, and never decodes
 * a game payload. A top-level BARE union would have worked too, but only by
 * teaching the Worker to parse commands — exactly what it is designed not to do.
 */
export const MessageTag = {
  Tick: 0,
  Created: 1,
  Start: 2,
  OpponentLeft: 3,
  Error: 4,
  // Chat shares the tag space but never the socket — it runs against a different
  // Durable Object. One space keeps `frame`/`tagOf` the only framing there is;
  // `Room` whitelists `Tick`, so these are dropped on a game socket, and the
  // game decoder throws on them for the mirror-image reason.
  ChatSend: 5,
  ChatHistory: 6,
  ChatPosted: 7,
  ChatPresence: 8,
} as const;
export type MessageTag = (typeof MessageTag)[keyof typeof MessageTag];

/**
 * Prepend the tag octet to an encoded payload. `opponentLeft` carries nothing, so
 * omitting the payload yields a one-byte frame.
 */
export function frame(tag: MessageTag, payload?: Uint8Array): Uint8Array<ArrayBuffer> {
  const bytes = new Uint8Array(1 + (payload?.length ?? 0));
  bytes[0] = tag;
  if (payload) bytes.set(payload, 1);
  return bytes;
}

/** The tag of a received frame, or `null` if it is empty or not a known tag. */
export function tagOf(frameBytes: ArrayBuffer): MessageTag | null {
  if (frameBytes.byteLength === 0) return null;
  const tag = new Uint8Array(frameBytes, 0, 1)[0];
  return isMessageTag(tag) ? tag : null;
}

/** The payload behind the tag octet, as a view — no copy. */
export function payloadOf(frameBytes: ArrayBuffer): Uint8Array {
  return new Uint8Array(frameBytes, 1);
}

function isMessageTag(value: number): value is MessageTag {
  for (const tag of Object.values(MessageTag)) if (tag === value) return true;
  return false;
}
