/**
 * Wire protocol for online matches between two human players. This module holds
 * the two things a BARE schema cannot express — the **handshake** (which happens
 * in URL query params, before any message can be sent) and the **framing** (one
 * tag octet in front of each payload). The message shapes themselves live in
 * `../schema/messages.bare` and reach code as `@drone-directive/protocol/codec`,
 * generated by `npm run codegen -w protocol` and committed.
 *
 * Nothing here has a runtime dependency, on purpose: the relay Worker imports
 * this module on its hot path and must be able to route a frame without linking
 * a decoder. See `.docs/multiplayer.md` and `.docs/server-relay.md`.
 */

/** Bumped on any breaking wire change; clients send it, the relay rejects mismatches. */
export const PROTOCOL_VERSION = 5;

/** Room codes: fixed length, drawn from an unambiguous alphabet (no 0/O/1/I). */
export const ROOM_CODE_LENGTH = 4;
export const ROOM_CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

/**
 * Connection contract. A WebSocket must target a specific room before it opens, so
 * the create/join intent travels as URL query params rather than as messages:
 *   host:  `?room=<CODE>&create=1&v=<PROTOCOL_VERSION>&mapSize=<small|medium|large>&ai=<0-2>`
 *   guest: `?room=<CODE>&v=<PROTOCOL_VERSION>`
 */
export const QueryParam = {
  Room: 'room',
  Create: 'create',
  Version: 'v',
  MapSize: 'mapSize',
  /** Bot-controlled sides joining the two humans, `0..MAX_AI_OPPONENTS`. */
  Ai: 'ai',
} as const;

/**
 * Most bots a networked match can seat. The map deals one corner per side and the
 * two humans already hold two of the four.
 */
export const MAX_AI_OPPONENTS = 2;

/** Map presets, as spelled in the `mapSize` query param (the handshake is still text). */
export const WIRE_MAP_SIZES = ['small', 'medium', 'large'] as const;
export type WireMapSize = (typeof WIRE_MAP_SIZES)[number];

/** How often a peer attaches a `WorldCheck` (in ticks) — ~1s at 10Hz. */
export const DESYNC_CHECK_EVERY = 10;

// ---------------------------------------------------------------------------
// Framing
// ---------------------------------------------------------------------------

/**
 * Which message a frame carries, as its leading octet. BARE has no envelope of
 * its own, and putting the discriminant *outside* the payload is what keeps the
 * relay dumb: it reads one byte to decide whether to forward, and never decodes
 * a game payload. A top-level BARE union would have worked too, but only by
 * teaching the Worker to parse commands — exactly what it is designed not to do.
 */
export const MessageTag = {
  Tick: 0,
  Created: 1,
  Start: 2,
  OpponentLeft: 3,
  Error: 4,
} as const;
export type MessageTag = (typeof MessageTag)[keyof typeof MessageTag];

/**
 * Prepend the tag octet to an encoded payload. `opponentLeft` carries nothing, so
 * omitting the payload yields a one-byte frame.
 */
export function frame(tag: MessageTag, payload?: Uint8Array): Uint8Array<ArrayBuffer> {
  const bytes = new Uint8Array(1 + (payload?.length ?? 0));
  bytes[0] = tag;
  if (payload) bytes.set(payload, 1);
  return bytes;
}

/** The tag of a received frame, or `null` if it is empty or not a known tag. */
export function tagOf(frameBytes: ArrayBuffer): MessageTag | null {
  if (frameBytes.byteLength === 0) return null;
  const tag = new Uint8Array(frameBytes, 0, 1)[0];
  return isMessageTag(tag) ? tag : null;
}

/** The payload behind the tag octet, as a view — no copy. */
export function payloadOf(frameBytes: ArrayBuffer): Uint8Array {
  return new Uint8Array(frameBytes, 1);
}

function isMessageTag(value: number): value is MessageTag {
  for (const tag of Object.values(MessageTag)) if (tag === value) return true;
  return false;
}
